/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function close(): void

export declare function getDeviceCount(): number

export declare function getDeviceName(index: number): string

/**
 * RDS (station name / radio text) metadata decoded from the same wideband
 * signal the audio path demodulates, inside the streaming thread. Pulled by
 * JS via `get_rds()` rather than pushed, since it only changes a few times a
 * minute — not worth a dedicated callback for.
 */
export declare function getRds(): RdsInfo

export declare function open(index: number): number

/**
 * RDS (station name / radio text) metadata decoded from the same wideband
 * signal the audio path demodulates. Pulled by JS via [`get_rds`] rather
 * than pushed, since it only changes a few times a minute.
 */
export interface RdsInfo {
  programId: number
  programType: string
  stationName?: string
  radioText?: string
}

/**
 * Starts streaming and delivers already-demodulated 16-bit PCM audio to
 * `callback`, ready to hand straight to the audio sink.
 *
 * Demodulation (phase extraction, resampling, de-emphasis, stereo/RDS decode)
 * happens inside the streaming thread set up below — desperado's tokio task,
 * or librtlsdr's own callback thread for the FFI fallback — never on whatever
 * thread calls into JS. The previous design called back into JS with raw IQ
 * bytes and ran the DSP as a synchronous native call from the JS callback,
 * which in practice meant Electron's main thread: once per IQ chunk, at the
 * full RTL-SDR sample rate. Under a throttled CPU (a power-saving governor,
 * or just a weaker SoC like a Raspberry Pi) that synchronous call could fall
 * behind real-time and block everything else on the main thread for as long
 * as it took to catch up — audio stutter and an unresponsive UI, same cause.
 */
export declare function readAsync(callback: (buf: Buffer) => void, outputRate: number): void

export declare function setFrequency(freq: number): number

/**
 * `gain < 0` selects automatic gain, matching the old C++ addon's `-1 = auto`
 * convention, expressed in tenths of dB like the rest of this API. Only takes
 * effect before streaming starts on the `desperado` backend — `RadioService`
 * never calls this while running. The `librtlsdr` fallback applies it immediately,
 * matching the old C++ addon.
 */
export declare function setGain(gain: number): void

export declare function setSampleRate(rate: number): number

export declare function stopAsync(): void
