/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * FM demodulation pipeline: phase-difference demodulation, adaptive resampling
 * down to the output rate, then de-emphasis. Exported as `FMPipeline` to match
 * the old C++ addon's JS-facing class name (`#[napi(js_name)]` below) — `clippy`
 * flags `FMPipeline` itself as an upper-case-acronym struct name.
 */
export declare class FMPipeline {
  constructor(inputRate: number, outputRate: number)
  /**
   * Clears decoded RDS state (PI/PS/RT/PTY) and re-syncs the stereo pilot PLL and
   * RDS demod chain. Call this after retuning — a new frequency means a different
   * station, so the old station's RDS data must not linger.
   */
  resetRds(): void
  process(buf: Buffer): Float32Array
  rds(): RdsInfo
}
export type FmPipeline = FMPipeline

export declare function close(): void

export declare function getDeviceCount(): number

export declare function getDeviceName(index: number): string

export declare function open(index: number): number

/**
 * RDS (station name / radio text) metadata decoded from the same wideband
 * signal the audio path demodulates. Pulled by JS via [`FmPipeline::rds`]
 * rather than pushed, since it only changes a few times a minute.
 */
export interface RdsInfo {
  programId: number
  programType: string
  stationName?: string
  radioText?: string
}

/**
 * Starts streaming and delivers each raw IQ chunk to `callback`. Mirrors the old
 * C++ addon's `readAsync(callback)` — the callback receives interleaved unsigned
 * 8-bit I/Q bytes, not demodulated audio.
 */
export declare function readAsync(callback: (buf: Buffer) => void): void

export declare function setFrequency(freq: number): number

/**
 * `gain < 0` selects automatic gain, matching the old C++ addon's `-1 = auto`
 * convention, expressed in tenths of dB like the rest of this API. Only takes
 * effect before streaming starts on the `desperado` backend — `RadioService`
 * never calls this while running. The `librtlsdr` fallback applies it immediately,
 * matching the old C++ addon.
 */
export declare function setGain(gain: number): void

export declare function setSampleRate(rate: number): number

export declare function stopAsync(): void
